version: 0.2
phases:
  install:
    runtime-versions:
      ubuntu: 18.04
  pre_build:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Builind the docker image"
      - cd result
      - docker build -t 306856845400.dkr.ecr.us-east-1.amazonaws.com/result:latest  .
  post_build:
    commands:
      - echo "Build completed successfully"
