version: 0.2

env:
  variables:
    ECR_REPO: "306856845400.dkr.ecr.us-east-1.amazonaws.com"
    REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO

      # OPTIONAL: Docker Hub auth to avoid pull limit errors
      #- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || echo "Skipping Docker Hub login"

      - BUILD_ID=${CODEBUILD_BUILD_NUMBER:-$(date +%Y%m%d%H%M%S)}
      - echo "Build ID: $BUILD_ID"
      - set -e

  build:
    commands:
      - echo "Building docker images in parallel"
      - docker build -t $ECR_REPO/result:$BUILD_ID ./result &
      - docker build -t $ECR_REPO/seed-data:$BUILD_ID ./seed-data &
      - docker build -t $ECR_REPO/vote:$BUILD_ID ./vote &
      - docker build -t $ECR_REPO/worker:$BUILD_ID ./worker &
      - wait

  post_build:
    commands:
      - echo "Pushing docker images to ECR"
      - docker push $ECR_REPO/result:$BUILD_ID &
      - docker push $ECR_REPO/seed-data:$BUILD_ID &
      - docker push $ECR_REPO/vote:$BUILD_ID &
      - docker push $ECR_REPO/worker:$BUILD_ID &
      - wait

artifacts:
  files:
    - '**/*'
