version: 0.2
env:
  variables:
    ECR_REPO: "306856845400.dkr.ecr.us-east-1.amazonaws.com"
    REGION: "us-east-1"
phases:
  pre_build:
    commands:
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo "Building docker images in parallel"
      - docker build -t $ECR_REPO/result:latest ./result &
      - docker build -t $ECR_REPO/seed-data:latest ./seed-data &
      - docker build -t $ECR_REPO/vote:latest ./vote &
      - docker build -t $ECR_REPO/worker:latest ./worker &
      - wait
  post_build:
    commands:
      - echo "Pushing docker images to ECR"
      - docker push $ECR_REPO/result:latest &
      - docker push $ECR_REPO/seed-data:latest &
      - docker push $ECR_REPO/vote:latest &
      - docker push $ECR_REPO/worker:latest &
      - wait
