version: 0.2
phases:
  pre_build:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Builind the docker image"
      - cd result
      - docker build -t 306856845400.dkr.ecr.us-east-1.amazonaws.com/result:latest  .
      - cd ../seed-data
      - docker build -t 306856845400.dkr.ecr.us-east-1.amazonaws.com/seed-data:latest  .
      - cd ../vote
      - docker build -t 306856845400.dkr.ecr.us-east-1.amazonaws.com/vote:latest  .
  post_build:
    commands:
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 306856845400.dkr.ecr.us-east-1.amazonaws.com
      - echo "Pushing the docker image to ECR"
      - docker push 306856845400.dkr.ecr.us-east-1.amazonaws.com/result:latest
      - docker push 306856845400.dkr.ecr.us-east-1.amazonaws.com/seed-data:latest
      - docker push 306856845400.dkr.ecr.us-east-1.amazonaws.com/vote:latest
